name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies (with dev)
        run: npm ci --legacy-peer-deps
        working-directory: ./

      - name: Run tests
        run: npm test
        working-directory: ./
        env:
          NODE_ENV: test

  build-frontend:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install production dependencies
        run: npm install --omit=dev --legacy-peer-deps
        working-directory: ./

      - name: Build frontend
        run: npm run build
        working-directory: ./
        continue-on-error: true

  deploy:
    needs: [test, build-frontend]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Render CLI
        run: curl -fsSL https://cli.render.com/install.sh | bash

      - name: Deploy to Render
        run: |
          render services deploy ${{ secrets.RENDER_SERVICE_ID }} \
            --token ${{ secrets.RENDER_API_KEY }} \
            --wait
        env:
          RENDER_INSTALL_COMMAND: npm install --omit=dev --legacy-peer-deps
          RENDER_START_COMMAND: npm start
